### ISSUE TITLE
EvilNotchLib  Overrides Custom Main Menu

### ISSUE THREAD

**Issue by IchigoGames** [jredfox/evilnotchlib#4]
Version:EvilNotchLib-1.2.3-SNAPSHOT-44
Issue: main menu is overriden by menu lib inside of cmm
Steps to reproduce:install custom main menu and evil notch lib

mods are 
EvilNotchLib-1.2.3-SNAPSHOT-44
ResourceLoader-MC1.12.1-1.5.3
CustomMainMenu-MC1.12.2-2.0.8
Forge 2738

**Comment by jredfox** [comment]
I don't know how I would be overriding custom main menu as I have a separate IResource pack are you sure you installed everything properly?

**Comment by jredfox** [comment]
The real issue here has nothing to do with my IResourcePack as my snapshot 55 has no IResourcePack. Even if it was the button of refresh would still appear on the main menu. 

What is actually happening is my multi menu library doesn't yet have manual support for custom main menu.

Me and my team are currently busy trying to push the next snapshot after that on our next list to do this will be one of the top priorities as there is already several issues with menu lib(allows multiple menus)

**Comment by IchigoGames** [comment]
well as it turns out i dont even use the mod this core mod is for anyway i just forgot it was there.

**Comment by jredfox** [comment]
well it will get fixed by the next release just use the latest release for now if possible. Thanks for reminding me.

This is a library and does contain a core mod for asm. The asm is vanilla bug fixes and don't effect gameplay besides fixing data getting lost(playerdata(uuid)). Also some other bug fixes like furnace and spawn eggs. Just a good mod to have(unless you have the beta then it's pretty crappy)

anyways it's going to be a while before I get around to fixing this since I am working on core features of said library so my other mods can function properly.

**Comment by jredfox** [comment]
after coding in hell for a while in asm and other crap I will be able to finally start writing a fix for this and other stuffs for menu lib. but, I am not quite out of the pit yet maybe within a week it should be fixed.

**Comment by jredfox** [comment]
cmm is doing everything wrong on their side. I will add support because I like this mod otherwise would simply close this and say side is theirs. 

I will replace their event handler class via asm as it's wrong. From there I should be able to figure out what's wrong and fix this issue here.

**Comment by jredfox** [comment]
I got it working there were many errors on the event handler and two errors in their main gui class I will convert to asm and have the mod working agin.
